### ISSUE TITLE
Cancel teleport when passing the end portal in combat

### ISSUE THREAD

**Issue by SrBedrock** [SirBlobman/CombatLogX#349]
### Server Implementation

Paper

### Server Version

1.17.1

### CombatLogX Version

![image](https://user-images.githubusercontent.com/51332006/147695104-76239c50-9c38-411d-b4f5-a6cf406d8673.png)

### Feature Request

Cancel teleport event when entering end portal during combat.

![image](https://user-images.githubusercontent.com/51332006/147695137-9ee8c315-c7c1-4e3b-ab09-20629250d307.png)

**Comment by SirBlobman** [comment]
This should be fixed in V11, if not please reopen this issue.

**Comment by SrBedrock** [comment]
Problem persists, a solution is cited in this issue https://github.com/PaperMC/Paper/pull/8941#issuecomment-1455223608
